### ISSUE TITLE
Configured, but Webhook doesn't work for some reason.

### ISSUE THREAD

**Issue by LucesEnBabel** [kalynrobinson/discord_integration#1]
Hello, I installed this plugin in my MyBB installation, configured the proper webhooks but doesn't work when I create a new thread.

**Settings**
New Thread Webhook:
https://discordapp.com/api/webhooks/(REDACTED)/(REDACTED)

New Thread Forums:
[*] Select Forums
1 forum selected

New Thread User Groups:
All groups

New Thread Discord Nickname:
_blank_

New Thread Discord Nessage[sic]:
```
[{$mybb->input["subject"]}]($threadurl)

$messageshort
```

New Reply Webhook:
_blank_

New Reply Forums:
None

New Reply User Groups:
None

New Reply Discord Nickname:
_blank_

New Reply Discord Message:
```
[{$mybb->user["username"]}]($userurl) posted in [{$mybb->input["subject"]}]($threadurl):

$messageshort
``` 
(default value)

Additional Webhooks:
```
webhook=https://discordapp.com/api/webhooks/(REDACTED)/(REDACTED)
behavior=new_topic
forums=26
message=[{$mybb->input["subject"]}]($threadurl)

$messageshort
---
```

MyBB Version 	1.8.10
PHP Version 	5.3.29
SQL Engine 	MySQLi 10.0.29
Server Load 	17.2

**Comment by kalynrobinson** [comment]
Please provide me with either a screenshot of your Discord Integration settings or copy and paste the values here. If you are comfortable with doing so, email me your webhook at kalyndrobinson@gmail.com.

Simple things that could be going wrong are, you either provided an incorrect webhook or you have your eligible forums and usergroups set up incorrectly. Double check that if you don't have those set to "all", you're posting in forums and as a group you've selected.

**Comment by LucesEnBabel** [comment]
Hello @kalynrobinson. I misclicked the submit issue button before I even added a detailed description of my Issue. I updated the OP accordingly.

**Comment by kalynrobinson** [comment]
@LucesEnBabel , at least for the additional webhook, new_topic should be new_thread. This was actually an inconsistency I had when developing—it's changed in the source code, but I just noticed it still said new_topic on the documentation page. I fixed that accordingly.

Does the general New Thread webhook work correctly?

**Comment by kalynrobinson** [comment]
Also, noticed the typo in New Thread Nessage and fixed that accordingly.

**Comment by LucesEnBabel** [comment]
Thank you.

Neither the general New Thread and the Additional webhooks work.

I still have the feeling the problem is on my end. Anything else I should check beforehand?

I failed to mention the plugin failed to install the first time and I had to forcefully remove it before MyBB installed it correctly.

**Comment by kalynrobinson** [comment]
@LucesEnBabel  I just pushed a fix for what I'm hoping is your problem, having to do with an improperly formatted avatar URL. You shouldn't have to reinstall it, just drop the corrected file discord_integration.php into your inc/plugins folder.

Can you describe how it failed to install? I've uninstalled and reinstalled dozens of times on my end and haven't encountered any problems.

**Comment by LucesEnBabel** [comment]
Thank you, installed the new version and it's working like a charm.

Also, there should be an option to use the Webhook's Default Name. I put it as a new issue #2
